name: huatai
version: 1

handlers:
- url: /robots.txt
  static_path: robots.txt
- url: /favicon.ico
  static_path: favicon.ico
- url: /static/
  static_path: huatai/static
  gzip: on

cron:
- description: cron_1
  url: /cron/5/1
  schedule: "*/5 * * * *"
- description: cron_2
  url: /cron/5/2
  schedule: "*/5 * * * *"
- description: cron_3
  url: /cron/5/3
  schedule: "*/5 * * * *"
- description: cron_4
  url: /cron/5/4
  schedule: "*/5 * * * *"
- description: cron_5
  url: /cron/5/5
  schedule: "*/5 * * * *"

