# configuration
DB_SCHEMA = 'mysql'
DB_HOST = 'SAE_MYSQL_HOST_M'
DB_PORT = 'SAE_MYSQL_PORT'
DB_USERNAME = 'SAE_MYSQL_USER'
DB_PASSWORD = 'SAE_MYSQL_PASS'
DATABASE = 'huatai'
DEBUG = False
#SQLALCHEMY_COMMIT_ON_TEARDOWN = True
